### ISSUE TITLE
compatible cm4 adapter

### ISSUE THREAD

**Issue by almowery** [will127534/OneInchEye#11]
I can't wait to use my one inch eye.  I have looked at all the cm4 adapter boards and only one says that it has a camera CSI-2 4 lane interface.  That one is Ochin.  This is a minimal board with no HDMI support.  I would prefer to have one with the HDMI port.  Can you recommend one?  I have  a PI 5 and that would be better.  I was not able to figure out how to compile the kernel.  Thanks.

**Comment by will127534** [comment]
It should work with RPI5 now : D
