### ISSUE TITLE
pcb problem

### ISSUE THREAD

**Issue by yassinebkr** [will127534/OneInchEye#15]
hello I'm trying to make the pcb from pcbway because there is some big shortages on jlcpcb and they ask me that : 
Hello Dear,
Thanks for your inquiry on PCBWay, this is Lynne.
As shown in attached screenshot.
1. The spacing between IC pins in circle is smaller than 0.22mm, cannot make soldermask bridge.
Could you accept to proceed without bridge?
Highly suggested to change the soldermask color from black to green/blue/red to make out the bridges,
in order to prevent solder paste connected cause the short circuit during assembly, is that ok for you? If yes, pls advise the new color option.
Or do you prefer to retain the current design and soldermask color, put this order to our high-quality factory to make out the soldermask bridge? If yes, price and build time both will increase, kindly noted that.

2. Some vias be designed on the SMD pads, pls advise if proceed with via-in-pad process?
If yes, this service is chargeable (over $100usd) and vias are to be non-conductive epoxy filled, plated over with copper and planarized.
If not, in order to guarantee assembly quality, it's suggested you can update design, move vias away from SMD pads and attach the new gerber files by email.
Looking forward to your reply.
![1](https://github.com/will127534/OneInchEye/assets/50209930/a467d28b-5969-4279-a2e7-600f9ff540fb)
![2](https://github.com/will127534/OneInchEye/assets/50209930/3c32ba99-0e1c-4522-89be-848dc40b5709)
what should I reply ?
Your  work is insane btw

yassine

**Comment by will127534** [comment]
1. That means the manufacture can not make the soldermask in between the pads, either you accept and take the risk of soldering short happening at those areas or you ask them to use a better PCB process that has higher cost.
2. Yes, you will need via-in-pad
