### ISSUE TITLE
Rpi5 Failed to start with OneInchEye camera attached

### ISSUE THREAD

**Issue by watchever** [will127534/OneInchEye#17]

**Comment by watchever** [comment]
I also add the JLCPCB gerber 2D viewer. Maybe a polarity issue ?
![image](https://github.com/will127534/OneInchEye/assets/14092607/4a09d9c7-390c-4f6e-8237-25f800281623)

**Comment by watchever** [comment]
Ok think I have found myself issue. The engraved on 22pins port are a mess.... Don't know why, like if Gerber files were corrupted.

**Comment by will127534** [comment]
I download the gerber straight from github and upload to jlcpcb and the render is perfect:
<img width="938" alt="Screenshot 2024-07-02 at 9 11 49 AM" src="https://github.com/will127534/OneInchEye/assets/6110733/40e2207b-bf16-4781-b3a4-af4d4c38a94e">

I don't know why you think the gerber is corrupted, literally zip it, upload it. Also I want to stress that if you are not familiar with PCB and or electrical engineer, please look else where.

**Comment by will127534** [comment]
There are multiple issues on your PCB board by the way

**Comment by watchever** [comment]
Hi Will, not saying that your PCB file is corrupted. It is by comparing my PCB file with yours that I found issues. So what I mean is my PCB files were modified in unexpected way by EasyEda. I have download Kicad files in EasyEda and generate gerber files with poor rendering. Really don't know why.

**Comment by watchever** [comment]
So if you find others issues in my PCB screenshot other than the wiring of the 22pins, please let me know.

**Comment by watchever** [comment]
Will, I know I am not a star with PCB. I do my best to learn, but if you can give me some advices to correct my mistakes on my previous PCB order, I will be really grateful. Maybe you will be happy to know that I plan to use the OneInchEye module for an astronomy project  which already use a IMX462 module but I want to upgrade to the IMX283. Thanks in advance for your time.

**Comment by watchever** [comment]
I confirm that importing the Kicad project in EasyEda generate erroneous wiring...
I'd rather state it for other users, than just saying like @will127534 that I should look elsewhere (useless reply).

![image](https://github.com/will127534/OneInchEye/assets/14092607/44483777-727d-4f49-a5b1-e9691f470f21)
